on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  runs-on: ubuntu-latest
  steps:
    run: pip install requirements.txt
    run: black --check --diff app.py
    run: isort --check --diff --profile black app.py
    run: flake8 app.py
    run: mypy app.py
    
