on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: pip install -r requirements.txt
      - run: black --check --diff *.py
      - run: isort --check --diff --profile black *.py
      - run: flake8 *.py
      - run: mypy *.py
    
