on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  runs-on: ubuntu
  steps:
    run: pip install requirements.txt
    run: black --check --diff *.py
    run: isort --check --diff --profile black *.py
    run: flake8 *.py
    run: mypy *.py
    
